import { styled } from "solid-styled-components";
import { createEffect, createSignal, Show, onMount } from "solid-js";
import { useNavigate } from "@solidjs/router";

export default function PrivacyPolicy() {
  return (
    <TermsContainer>
      <TermHeader>
        <h1>Privacy Policy</h1>

        <Term>
          <p>
            Tweet Cycle (“us”, “we”, or “our”) operates the Tweet Cycle website
            and Tweet Cycle mobile application (hereinafter referred to as
            “Service”). This page informs you of our policies regarding the
            collection, use, and disclosure of personal data when you use our
            Service and the choices you have associated with that data.
          </p>

          <p>
            We use your data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions, accessible from
            tweetcycle.com.
          </p>
        </Term>

        <h2>Definitions</h2>

        <Term>
          <TermTitle>Service</TermTitle>
          <TermBody>
            Service is the Tweet Cycle website and Tweet Cycle mobile
            application operated by Tweet Cycle
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Personal Data</TermTitle>
          <TermBody>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Usage Data</TermTitle>
          <TermBody>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Cookies</TermTitle>
          <TermBody>
            Cookies are small files stored on your device (computer or mobile
            device).
          </TermBody>
        </Term>

        <h2>Information Collection and Use</h2>

        <Term>
          <TermTitle>Personal Data</TermTitle>
          <TermBody>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to: Email address Twitter handle
            First name and last name Phone number Address, State, Province,
            ZIP/Postal code, City Cookies and Usage Data.
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Usage Data</TermTitle>
          <TermBody>
            We may also collect information how the Service is accessed and used
            (“Usage Data”). This Usage Data may include information such as your
            computers Internet Protocol address (e.g. IP address), browser type,
            browser version, the pages of our Service that you visit, the time
            and date of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Tracking & Cookies Data</TermTitle>
          <TermBody>
            <p>
              We use cookies and similar tracking technologies to track the
              activity on our Service and hold certain information. Cookies are
              files with small amount of data which may include an anonymous
              unique identifier. Cookies are sent to your browser from a web
              site and stored on your device. Tracking technologies also used
              are beacons, tags, and scripts to collect and track information
              and to improve and analyze our Service.
            </p>

            <p>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
              Examples of Cookies we use: Session Cookies. We use Session
              Cookies to operate our Service.
            </p>

            <p>
              Preference Cookies.
              <br />
              We use Preference Cookies to remember your preferences and various
              settings.
              <br />
              <br />
              Security Cookies.
              <br />
              We use Security Cookies for security purposes.
              <br />
              <br />
              Use of Data Tweet Cycle uses the collected data for various
              purposes:
              <br />
              <br />
              To provide and maintain the Service To notify you about changes to
              our Service To allow you to participate in interactive features of
              our Service when you choose to do so To provide customer care and
              support To provide analysis or valuable information so that we can
              improve the Service To monitor the usage of the Service To detect,
              prevent and address technical issues
            </p>
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Transfer Of Data</TermTitle>
          <TermBody>
            Your information, including Personal Data, may be transferred to —
            and maintained on — computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ than those from your jurisdiction. If you
            are located outside United States and choose to provide information
            to us, please note that we transfer the data, including Personal
            Data, to United States and process it there. Your consent to this
            Privacy Policy followed by your submission of such information
            represents your agreement to that transfer. Tweet Cycle will take
            all steps reasonably necessary to ensure that your data is treated
            securely and in accordance with this Privacy Policy and no transfer
            of your Personal Data will take place to an organization or a
            country unless there are adequate controls in place including the
            security of your data and other personal information.
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Disclosure Of Data</TermTitle>
          <TermBody>
            <p>
              Legal Requirements Tweet Cycle may disclose your Personal Data in
              the good faith belief that such action is necessary to: To comply
              with a legal obligation To protect and defend the rights or
              property of Tweet Cycle To prevent or investigate possible
              wrongdoing in connection with the Service To protect the personal
              safety of users of the Service or the public To protect against
              legal liability Security Of Data The security of your data is
              important to us, but remember that no method of transmission over
              the Internet, or method of electronic storage is 100% secure.
              While we strive to use commercially acceptable means to protect
              your Personal Data, we cannot guarantee its absolute security.
            </p>
            <p>
              Service Providers We may employ third party companies and
              individuals to facilitate our Service (“Service Providers”), to
              provide the Service on our behalf, to perform Service-related
              services or to assist us in analyzing how our Service is used.
              These third parties have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose. Analytics We may use
              third-party Service Providers to monitor and analyze the use of
              our Service.
            </p>
            <p>
              Google Analytics Google Analytics is a web analytics service
              offered by Google that tracks and reports website traffic. Google
              uses the data collected to track and monitor the use of our
              Service. This data is shared with other Google services. Google
              may use the collected data to contextualize and personalize the
              ads of its own advertising network. You can opt-out of having made
              your activity on the Service available to Google Analytics by
              installing the Google Analytics opt-out browser add-on. The add-on
              prevents the Google Analytics JavaScript (ga.js, analytics.js, and
              dc.js) from sharing information with Google Analytics about visits
              activity. For more information on the privacy practices of Google,
              please visit the Google Privacy & Terms web page:
              https://policies.google.com/privacy?hl=en Links To Other Sites Our
              Service may contain links to other sites that are not operated by
              us.
            </p>
            <p>
              If you click on a third party link, you will be directed to that
              third party’s site. We strongly advise you to review the Privacy
              Policy of every site you visit. We have no control over and assume
              no responsibility for the content, privacy policies or practices
              of any third party sites or services. Children’s Privacy Our
              Service does not address anyone under the age of 18 (“Children”).
              We do not knowingly collect personally identifiable information
              from anyone under the age of 18. If you are a parent or guardian
              and you are aware that your Children has provided us with Personal
              Data, please contact us. If we become aware that we have collected
              Personal Data from children without verification of parental
              consent, we take steps to remove that information from our
              servers.
            </p>

            <p>
              Changes To This Privacy Policy We may update our Privacy Policy
              from time to time. We will notify you of any changes by posting
              the new Privacy Policy on this page. We will let you know via
              email and/or a prominent notice on our Service, prior to the
              change becoming effective and update the “effective date” at the
              top of this Privacy Policy. You are advised to review this Privacy
              Policy periodically for any changes. Changes to this Privacy
              Policy are effective when they are posted on this page. Contact Us
              If you have any questions about this Privacy Policy, please
              contact us: By email: support@tweetcycle.com By visiting this page
              on our website: https://tweetcycle.com/contact
            </p>
          </TermBody>
        </Term>

        <Term>
          <TermTitle>Disclaimer</TermTitle>
          <TermBody>
            <p>
              Tweet Cycle is a social media management tool that allows users to
              schedule and post content to their social media accounts.
              TweetCycle.com is not affiliated with Twitter, Inc. or any other
              social media platform. All trademarks, service marks, trade names,
              trade dress, product names and logos appearing on the site are the
              property of their respective owners.
            </p>
            All other trademarks not owned by Tweet Cycle that appear on this
            site are the property of their respective owners, who may or may not
            be affiliated with, connected to, or sponsored by Tweet Cycle. Tweet
            Cycle is not responsible for the content of any linked site, any
            link contained in a linked site, or any changes or updates to such
            sites. Tweet Cycle is providing these links to you only as a
            convenience, and the inclusion of any link does not imply
            endorsement by Tweet Cycle of the site or any association with its
            operators. Tweet Cycle is not responsible for webcasting or any
            other form of transmission received from any linked site.
          </TermBody>
        </Term>
      </TermHeader>
    </TermsContainer>
  );
}

const TermsContainer = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
  padding: 10px;
  font-family: "Poppins", sans-serif;
`;

const TermHeader = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
  padding: 10px;
  font-family: "Poppins", sans-serif;
  margin-top: 100px;
`;

const Term = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  width: 50%;
  gap: 10px;

  @media (max-width: 768px) {
    width: 100%;
  }
`;

const TermTitle = styled("div")`
  display: flex;
  font-size: larger;
  font-weight: bold;
  margin-right: 10px;
  color: "#1D9BF0" !important;
`;

const TermBody = styled("div")`
  display: flex;
  flex-direction: column;
  font-weight: normal;
`;

const ListDiv = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
  padding: 10px;
  font-family: "Poppins", sans-serif;
  background-color: aliceblue;
`;
